#!/usr/bin/env bash

set -e
HOST=http://sublime.simplesideias.com.br troy export
find . -name .DS_Store -exec rm {} \;
rsync --delete -vr --partial --progress -e ssh public www-data@sublime.simplesideias.com.br:/var/www/sublime-screencasts/
